# Generated by Django 5.2.8 on 2026-06-17 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('rule_based', 'Rule Based'), ('ai_assisted', 'AI Assisted')], default='rule_based', max_length=30)),
                ('engine_version', models.CharField(default='rule_based_v1', max_length=60)),
                ('summary', models.TextField(blank=True)),
                ('safety_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_logs', to='products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('product_name_snapshot', models.CharField(max_length=180)),
                ('safety_note_snapshot', models.TextField(blank=True)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_prescription_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_items', to='products.product')),
                ('recommendation_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_assistant.recommendationlog')),
            ],
            options={
                'ordering': ['rank', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('adult', 'Adult'), ('senior', 'Senior'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('has_emergency_symptoms', models.BooleanField(default=False)),
                ('emergency_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('blocked_emergency', 'Blocked Emergency'), ('no_match', 'No Match')], default='completed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='ai_assistant.symptomsession'),
        ),
    ]
