# Generated by Django 5.2.8 on 2026-06-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_normalize_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
